name:call


on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update unlisted
      run: curl 
    # - name: Deploy to server port:80
    #   run: curl https://born-to-llama.herokuapp.com/rebuild-server
